module.exports = {
  REQUEST: {
    CONNECTION: 'socket/GAME_CONNECTION_REQUEST',
    EXIT: 'socket/EXIT_GAME_REQUEST',
    INPUT: 'socket/INPUT_REQUEST',
    START: 'socket/START_GAME_REQUEST'
  },
  RESPONSE: {
    CONNECTION: 'socket/GAME_CONNECTION_RESPONSE',
    ENTRIES: 'socket/ENTRIES_RESPONSE',
    ERROR: 'socket/CLIENT_ERROR_RESPONSE',
    EXIT: 'socket/EXIT_GAME_RESPONSE',
    FINISH: 'socket/GAME_FINISH_RESPONSE',
    RESULT: 'socket/RESULT_NUMBER_RESPONSE',
    START: 'socket/START_GAME_RESPONSE',
    TURN: 'socket/TURN_RESPONSE'
  }
};
